<?php

/**
 * @file
 * Defines the abstract class for Checksum veritfication.
 */
namespace App\Plugin;

/**
 * Abstract class for the Checksum vertification plugin
 */
abstract class AbstractVerifyChecksumPlugin {

    
    /**
     * Constructor.
     * 
     * @param array $settings
     *    The configuration data from the settings file.
     * @param object $logger
     *    The Monolog logger from the main Console command.
     */
    public function __construct($settings, $logger){
        $this->settings = $settings;
        $this->logger = $logger;

        if (isset($this->settings['verify']) && $this->settings['verify']) {
            $this->verify = true;
        } else {
            $this->verify = false;
        }
        
    }

 /**
  * Verifies the checksum generated by the Drupal algorithm against the FITS checksum
  *
  * @param string $resource_id
  *     The resource ID of the file
  *
  * @param string $comparison_checksum
  *     The checksum value that Riprap is using
  * 
  * @return bool
  *     True if it is equal, False if mismatch or error
  */
    public abstract function execute($resource_id, $comparison_checksum);
}